export const CLASSES=["status_only_recovery","read_only_check","deterministic_extraction","ordinary_provider_operation","implementation","incident_response","critical_production_acceptance","unknown"] as const;
export type Pilot={mode:"shadow";taskClass:typeof CLASSES[number];confidence:"high"|"low";conflictingSignals:boolean;consecutiveEquivalentFailures:number;protections:Record<string,boolean>;providerOperation?:{reversible:boolean;nonProduction:boolean;alreadyAuthorized:boolean;bounded:boolean}};
export type Decision={mode:"shadow";taskClass:Pilot["taskClass"];proposedLane:"economy"|"strongest";appliedLane:"strongest";decisionReason:string;escalationReason:"uncertainty"|"repeated_failure"|"protected_action"|"profile_fallback"|null;profileFallbackReason:string|null};
const keys=["productionOrPublish","destructiveOrIrreversible","credentialsOrSecrets","approvalOrGovernance","securityOrForensics","criticalAcceptance","materiallyExpandedScope"],routine=new Set(CLASSES.slice(0,4));
const invalidPilot=():Pilot=>({mode:"shadow",taskClass:"unknown",confidence:"low",conflictingSignals:false,consecutiveEquivalentFailures:0,protections:Object.fromEntries(keys.map(k=>[k,false]))});
export function parsePilot(v:any):Pilot|null{if(v==null)return null;return typeof v==="object"&&v.mode==="shadow"&&CLASSES.includes(v.taskClass)&&["high","low"].includes(v.confidence)&&typeof v.conflictingSignals==="boolean"&&Number.isInteger(v.consecutiveEquivalentFailures)&&v.consecutiveEquivalentFailures>=0&&v.protections&&keys.every(k=>typeof v.protections[k]==="boolean")?v:invalidPilot()}
const strong=(p:Pilot,r:string,e:Decision["escalationReason"],f:string|null=null):Decision=>({mode:"shadow",taskClass:p.taskClass,proposedLane:"strongest",appliedLane:"strongest",decisionReason:r,escalationReason:e,profileFallbackReason:f});
export function decideShadowRouting(p:Pilot|null,f:string|null):Decision|null{if(!p)return null;if(p.taskClass==="unknown")return strong(p,"insufficient_signal","uncertainty");if(p.confidence==="low"||p.conflictingSignals)return strong(p,"escalated","uncertainty");if(keys.some(k=>p.protections[k]))return strong(p,"escalated","protected_action");if(p.consecutiveEquivalentFailures>=2)return strong(p,"escalated","repeated_failure");if(!routine.has(p.taskClass))return strong(p,"strongest_task_class",null);if(p.taskClass==="ordinary_provider_operation"&&(!p.providerOperation||!Object.values(p.providerOperation).every(Boolean)))return strong(p,p.providerOperation?"escalated":"insufficient_signal",p.providerOperation?"protected_action":"uncertainty");if(f)return strong(p,"escalated","profile_fallback",f);return{mode:"shadow",taskClass:p.taskClass,proposedLane:"economy",appliedLane:"strongest",decisionReason:"routine_candidate",escalationReason:null,profileFallbackReason:null}}
type M={processedTokens:number;uncachedInputTokens:number;cachedInputTokens:number;outputTokens:number;paidCostCents:number};
export function buildShadowCohortReport(rows:Array<{issueId:string;cohortKey:string;metrics:M}>,members:Array<{issueId:string;decision:Decision}>){const d=new Map(members.map(x=>[x.issueId,x.decision])),shadow=rows.filter(x=>d.has(x.issueId)),names=["processedTokens","uncachedInputTokens","cachedInputTokens","outputTokens","paidCostCents"] as const;const metrics=Object.fromEntries(names.map(n=>{let actualShadow=0,baselineP50=0;for(const r of shadow){actualShadow+=r.metrics[n];const p=rows.filter(x=>x.cohortKey===r.cohortKey&&!d.has(x.issueId)).map(x=>x.metrics[n]).sort((a,b)=>a-b);if(p.length){const m=(p.length-1)/2;baselineP50+=((p[Math.floor(m)]??0)+(p[Math.ceil(m)]??0))/2}}return[n,{actualShadow,baselineP50,actualDeltaFromBaseline:actualShadow-baselineP50}]}));return{sampleSize:shadow.length,economyProposalCount:shadow.filter(x=>d.get(x.issueId)?.proposedLane==="economy").length,strongestProposalCount:shadow.filter(x=>d.get(x.issueId)?.proposedLane==="strongest").length,metrics,counterfactualEstimate:null}}