export const CLASSES=["status_only_recovery","read_only_check","deterministic_extraction","ordinary_provider_operation","implementation","incident_response","critical_production_acceptance","unknown"] as const;
export type Pilot={mode:"shadow";taskClass:typeof CLASSES[number];confidence:"high"|"low";conflictingSignals:boolean;consecutiveEquivalentFailures:number;protections:Record<string,boolean>;providerOperation?:{reversible:boolean;nonProduction:boolean;alreadyAuthorized:boolean;bounded:boolean}};
export type Decision={mode:"shadow";taskClass:Pilot["taskClass"];proposedLane:"economy"|"strongest";appliedLane:"strongest";decisionReason:string;escalationReason:"uncertainty"|"repeated_failure"|"protected_action"|"profile_fallback"|null;profileFallbackReason:string|null};
type ClassificationInput={issue:{title:string;description:string|null;workMode:string;status:string}|null;wakeReason:string|null;scheduledRetryAttempt:number};
/** Server-owned classification at the persisted issue/wake/run execution boundary. */
export function classifyShadowPilot(input:ClassificationInput):Pilot|null{if(!input.issue)return null;const text=`${input.issue.title}\n${input.issue.description??""}`.toLowerCase(),wake=input.wakeReason?.toLowerCase()??"",has=(r:RegExp)=>r.test(text),protections:Pilot["protections"]={productionOrPublish:has(/\b(production|prod|publish|release|deploy)\b/),destructiveOrIrreversible:has(/\b(delete|destroy|drop|irreversible|migration)\b/),credentialsOrSecrets:has(/\b(credential|secret|token|password|api key)\b/),approvalOrGovernance:has(/\b(approval|approve|governance|board decision)\b/),securityOrForensics:has(/\b(security|vulnerability|forensic|incident)\b/),criticalAcceptance:has(/\b(critical acceptance|release acceptance|production acceptance)\b/),materiallyExpandedScope:has(/\b(cross[- ]system|company[- ]wide|repo[- ]wide)\b/)};let taskClass:Pilot["taskClass"]="unknown";if(/status|recovery|retry|continuation/.test(wake)&&has(/\b(status|recover|resume|retry|continue)\b/))taskClass="status_only_recovery";else if(has(/\b(inspect|check|audit|report|review|readback|diagnos|investigat|verify)\b/))taskClass="read_only_check";else if(has(/\b(extract|classif|parse|normalize|summari[sz]e|transform)\b/))taskClass="deterministic_extraction";else if(has(/\b(webhook|provider|integration|sync|deliver|upload|archive|metadata|configuration|config)\b/))taskClass="ordinary_provider_operation";else if(has(/\b(implement|add|build|fix|change|refactor|update|create)\b/))taskClass="implementation";else if(has(/\b(outage|incident|degraded|emergency)\b/))taskClass="incident_response";if(protections.productionOrPublish||protections.criticalAcceptance)taskClass="critical_production_acceptance";const pilot:Pilot={mode:"shadow",taskClass,confidence:taskClass==="unknown"?"low":"high",conflictingSignals:false,consecutiveEquivalentFailures:Math.max(0,input.scheduledRetryAttempt),protections};if(taskClass==="ordinary_provider_operation")pilot.providerOperation={reversible:!protections.destructiveOrIrreversible,nonProduction:!protections.productionOrPublish,alreadyAuthorized:!protections.approvalOrGovernance,bounded:!protections.materiallyExpandedScope};return pilot}
export function persistShadowRoutingDecision(resultJson:Record<string,unknown>,decision:Decision|null){return decision?{...resultJson,paperclipRoutingDecision:decision}:resultJson}
export function parseDecision(value:unknown):Decision|null{if(!value||typeof value!=="object"||Array.isArray(value))return null;const d=value as Decision;return d.mode==="shadow"&&CLASSES.includes(d.taskClass)&&["economy","strongest"].includes(d.proposedLane)&&d.appliedLane==="strongest"?d:null}
const keys=["productionOrPublish","destructiveOrIrreversible","credentialsOrSecrets","approvalOrGovernance","securityOrForensics","criticalAcceptance","materiallyExpandedScope"],routine=new Set(CLASSES.slice(0,4));
const invalidPilot=():Pilot=>({mode:"shadow",taskClass:"unknown",confidence:"low",conflictingSignals:false,consecutiveEquivalentFailures:0,protections:Object.fromEntries(keys.map(k=>[k,false]))});
export function parsePilot(v:any):Pilot|null{if(v==null)return null;return typeof v==="object"&&v.mode==="shadow"&&CLASSES.includes(v.taskClass)&&["high","low"].includes(v.confidence)&&typeof v.conflictingSignals==="boolean"&&Number.isInteger(v.consecutiveEquivalentFailures)&&v.consecutiveEquivalentFailures>=0&&v.protections&&keys.every(k=>typeof v.protections[k]==="boolean")?v:invalidPilot()}
const strong=(p:Pilot,r:string,e:Decision["escalationReason"],f:string|null=null):Decision=>({mode:"shadow",taskClass:p.taskClass,proposedLane:"strongest",appliedLane:"strongest",decisionReason:r,escalationReason:e,profileFallbackReason:f});
export function decideShadowRouting(p:Pilot|null,f:string|null):Decision|null{if(!p)return null;if(p.taskClass==="unknown")return strong(p,"insufficient_signal","uncertainty");if(p.confidence==="low"||p.conflictingSignals)return strong(p,"escalated","uncertainty");if(keys.some(k=>p.protections[k]))return strong(p,"escalated","protected_action");if(p.consecutiveEquivalentFailures>=2)return strong(p,"escalated","repeated_failure");if(!routine.has(p.taskClass))return strong(p,"strongest_task_class",null);if(p.taskClass==="ordinary_provider_operation"&&(!p.providerOperation||!Object.values(p.providerOperation).every(Boolean)))return strong(p,p.providerOperation?"escalated":"insufficient_signal",p.providerOperation?"protected_action":"uncertainty");if(f)return strong(p,"escalated","profile_fallback",f);return{mode:"shadow",taskClass:p.taskClass,proposedLane:"economy",appliedLane:"strongest",decisionReason:"routine_candidate",escalationReason:null,profileFallbackReason:null}}
type M={processedTokens:number;uncachedInputTokens:number;cachedInputTokens:number;outputTokens:number;paidCostCents:number};
export type ShadowCohortRow={issueId:string;cohortKey:string;metrics:M;outcome:{firstPassAccepted:boolean;reopened:boolean}};
const threshold=5,rate=(count:number,total:number)=>total?count/total:null,summarize=(rows:ShadowCohortRow[],key:"firstPassAccepted"|"reopened")=>{const count=rows.filter(row=>row.outcome[key]).length;return{count,total:rows.length,rate:rate(count,rows.length)}};
export function buildShadowCohortReport(rows:ShadowCohortRow[],members:Array<{issueId:string;decision:Decision}>){const d=new Map(members.map(x=>[x.issueId,x.decision])),shadow=rows.filter(x=>d.has(x.issueId)),cohorts=new Set(shadow.map(x=>x.cohortKey)),control=rows.filter(x=>!d.has(x.issueId)&&cohorts.has(x.cohortKey)),names=["processedTokens","uncachedInputTokens","cachedInputTokens","outputTokens","paidCostCents"] as const;const metrics=Object.fromEntries(names.map(n=>{let actualShadow=0,baselineP50=0;for(const r of shadow){actualShadow+=r.metrics[n];const p=rows.filter(x=>x.cohortKey===r.cohortKey&&!d.has(x.issueId)).map(x=>x.metrics[n]).sort((a,b)=>a-b);if(p.length){const m=(p.length-1)/2;baselineP50+=((p[Math.floor(m)]??0)+(p[Math.ceil(m)]??0))/2}}return[n,{actualShadow,baselineP50,actualDeltaFromBaseline:actualShadow-baselineP50}]})),sa=summarize(shadow,"firstPassAccepted"),sr=summarize(shadow,"reopened"),ca=control.length?summarize(control,"firstPassAccepted"):null,cr=control.length?summarize(control,"reopened"):null,ad=sa.rate!==null&&ca!==null&&ca.rate!==null?(sa.rate-ca.rate)*100:null,rd=sr.rate!==null&&cr!==null&&cr.rate!==null?(sr.rate-cr.rate)*100:null,ar=ad===null?null:ad < -threshold,rr=rd===null?null:rd > threshold;return{sampleSize:shadow.length,economyProposalCount:shadow.filter(x=>d.get(x.issueId)?.proposedLane==="economy").length,strongestProposalCount:shadow.filter(x=>d.get(x.issueId)?.proposedLane==="strongest").length,outcomes:{materialRegressionRule:{thresholdPercentagePoints:threshold,description:"Block when shadow first-pass acceptance is more than 5 percentage points lower than control or shadow reopen rate is more than 5 percentage points higher than control."},firstPassAcceptance:{shadow:sa,control:ca,deltaPercentagePoints:ad,materiallyRegressed:ar},reopen:{shadow:sr,control:cr,deltaPercentagePoints:rd,materiallyRegressed:rr},verdict:control.length===0?"insufficient_control":ar||rr?"block":"pass"},metrics,counterfactualEstimate:null}}
